scale in nodes success

diff --git a/self/redis-cluster/templates/scale-down-job.yaml b/self/redis-cluster/templates/scale-down-job.yaml
--- a/self/redis-cluster/templates/scale-down-job.yaml
+++ b/self/redis-cluster/templates/scale-down-job.yaml
@@ -2,14 +2,14 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: {{ template "common.names.fullname" . }}-cluster-update
+  name: {{ template "common.names.fullname" . }}-cluster-down
   namespace: {{ .Release.Namespace | quote }}
   labels: {{- include "common.labels.standard" . | nindent 4 }}
     {{- if .Values.commonLabels }}
     {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
     {{- end }}
   annotations:
-    "helm.sh/hook": post-upgrade
+    "helm.sh/hook": pre-upgrade
     {{- if .Values.updateJob.annotations }}
     {{- include "common.tplvalues.render" ( dict "value" .Values.updateJob.annotations "context" $ ) | nindent 4 }}
     {{- end }}
@@ -84,97 +84,48 @@ spec:
                   cp /opt/pacloud/redis/etc/redis-default.conf /opt/pacloud/redis/etc/redis.conf
               fi
               firstNodeIP=$(wait_for_dns_lookup {{ template "common.names.fullname" . }}-0.{{ template "common.names.fullname" . }}-headless 120 5)
-              {{- if .Values.cluster.externalAccess.enabled }}
-              newNodeCounter=0
-              for nodeIP in $(echo "{{ .Values.cluster.update.newExternalIPs }}" | cut -d [ -f2 | cut -d ] -f 1 ); do
-                {{- if .Values.tls.enabled }}
-                while [[ $(redis-cli -h "$nodeIP" -p "$REDIS_TLS_PORT_NUMBER" --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} ping) != 'PONG' ]]; do
-                {{- else }}
-                while [[ $(redis-cli  -a $REDISCLI_AUTH -h "$nodeIP" -p "$REDIS_PORT_NUMBER" ping) != 'PONG' ]]; do
-                {{- end }}
-                  echo "Node $nodeIP not ready, waiting for all the nodes to be ready..."
-                  sleep 5
-                done
-                slave=()
-                if (( $REDIS_CLUSTER_REPLICAS >= 1 )) && (( newNodeCounter % (( $REDIS_CLUSTER_REPLICAS + 1 )) )); then
-                  slave+=("--cluster-slave")
-                fi
-                {{- if .Values.tls.enabled }}
-                while ! redis-cli --cluster --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} add-node "${nodeIP}:${REDIS_TLS_PORT_NUMBER}" "{{ index .Values.cluster.externalAccess.service.loadBalancerIP 0 }}:${REDIS_TLS_PORT_NUMBER}" ${slave[@]}; do
-                {{- else }}
-                while ! redis-cli -a $REDISCLI_AUTH --cluster add-node "${nodeIP}:${REDIS_PORT_NUMBER}" "{{ index .Values.cluster.externalAccess.service.loadBalancerIP 0 }}:${REDIS_PORT_NUMBER}" ${slave[@]}; do
-                {{- end }}
-                  echo "Add-node ${newNodeIndex} ${newNodeIP} failed, retrying"
-                  sleep 5
-                done
-                ((newNodeCounter += 1))
-              done
-
-              {{- if .Values.tls.enabled }}
-              while ! redis-cli --cluster rebalance --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} "{{ index .Values.cluster.externalAccess.service.loadBalancerIP 0 }}:${REDIS_TLS_PORT_NUMBER}" --cluster-use-empty-masters; do
-              {{- else }}
-              while ! redis-cli -a $REDISCLI_AUTH --cluster rebalance "{{ index .Values.cluster.externalAccess.service.loadBalancerIP 0 }}:${REDIS_PORT_NUMBER}" --cluster-use-empty-masters; do
-              {{- end }}
-                echo "Rebalance failed, retrying"
-                sleep 5
-                {{- if .Values.tls.enabled }}
-                redis-cli --cluster fix --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} "{{ index .Values.cluster.externalAccess.service.loadBalancerIP 0 }}:${REDIS_TLS_PORT_NUMBER}"
-                {{- else }}
-                redis-cli -a $REDISCLI_AUTH --cluster fix "{{ index .Values.cluster.externalAccess.service.loadBalancerIP 0 }}:${REDIS_PORT_NUMBER}"
-                {{- end }}
-              done
-
-              {{- else }}
+              # find the first node_id
+              firstNodeID=$(redis-cli -a $REDISCLI_AUTH -h "$firstNodeIP" -p "$REDIS_PORT_NUMBER" cluster nodes | grep myself | awk '{print $1}')
               # number of currently deployed redis master nodes
-              currentMasterNodesNum="$(( {{ .Values.cluster.update.currentNumberOfNodes }} / (( {{ .Values.cluster.update.currentNumberOfReplicas }} + 1 )) ))"
-              # end postion of new replicas that should be assigned to original redis master nodes
-              slaveNodesEndPos="$(( {{ .Values.cluster.update.currentNumberOfNodes }} + (($REDIS_CLUSTER_REPLICAS - {{ .Values.cluster.update.currentNumberOfReplicas }})) * $currentMasterNodesNum ))"
-              for node in $(seq $((1+{{ .Values.cluster.update.currentNumberOfNodes }})) {{ .Values.cluster.nodes }}); do
-                newNodeIndex="$(($node - 1))"
-                newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
-                {{- if .Values.tls.enabled }}
-                while [[ $(redis-cli -h "$newNodeIP" -p "$REDIS_TLS_PORT_NUMBER" --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} ping) != 'PONG' ]]; do
-                {{- else }}
-                while [[ $(redis-cli  -a $REDISCLI_AUTH -h "$newNodeIP" -p "$REDIS_PORT_NUMBER" ping) != 'PONG' ]]; do
-                {{- end }}
+              currentNodeOfNum={{ .Values.cluster.update.currentNumberOfNodes }}
+              for node in $(seq {{ .Values.cluster.nodes }} $(({{ .Values.cluster.update.currentNumberOfNodes }} - 1)) ); do
+                delNodeIndex=$node
+                delNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${delNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
+                while [[ $(redis-cli  -a $REDISCLI_AUTH -h "$delNodeIP" -p "$REDIS_PORT_NUMBER" ping) != 'PONG' ]]; do
                   echo "Node $newNodeIP not ready, waiting for all the nodes to be ready..."
-                  newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
+                  delNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${delNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
                   sleep 5
                 done
-                slave=()
-                # when the index of the new node is less than `slaveNodesEndPos`，the added node is a replica that assigned to original redis master node
-                # when the index of the new node is greater than or equal to `slaveNodesEndPos`，and it is not a multiple of `$REDIS_CLUSTER_REPLICAS + 1`, the added node is a replica that assigned to newly added master node
-                if (( $REDIS_CLUSTER_REPLICAS >= 1 )) && (( (( $newNodeIndex < $slaveNodesEndPos )) || (( (( $newNodeIndex >= $slaveNodesEndPos )) && (( $newNodeIndex % (( $REDIS_CLUSTER_REPLICAS + 1 )) )) )) )); then
-                  slave+=("--cluster-slave")
+
+                currentNodeID=$(redis-cli -a $REDISCLI_AUTH -h $delNodeIP -p $REDIS_PORT_NUMBER cluster nodes | grep myself | awk '{print $1}')
+                delRedisRule=$(redis-cli -a $REDISCLI_AUTH -h $delNodeIP -p $REDIS_PORT_NUMBER cluster nodes | grep myself | awk '{print $3}' | awk -F "," '{print $2}')
+                echo "find the delNodeID: $currentNodeID, delRedisRule: $delRedisRule"
+                if [[ $delRedisRule == 'master' ]]; then
+
+                  # get the slots_num on current delNode
+                  slots_num=$(redis-cli -a $REDISCLI_AUTH --cluster check $firstNodeIP:$REDIS_PORT_NUMBER | grep $delNodeIP| grep slots | awk '{print $7}')
+                  echo "-------current_index:$delNodeIndex ip:$delNodeIP find slots_num: $slots_num--------------"
+                  # reshard slots_num to first nodes
+                  redis-cli --cluster reshard $firstNodeIP:$REDIS_PORT_NUMBER --cluster-from $currentNodeID --cluster-to $firstNodeID --cluster-slots $slots_num --cluster-yes
+                  echo "reshard slots_num: $slots_num to first nodes, #?"
+                  # delete delNode
+                  redis-cli -a $REDISCLI_AUTH --cluster del-node $firstNodeIP:$REDIS_PORT_NUMBER $currentNodeID
+                  echo "delete delNode, #@?"
+                else
+                  # delete delNode
+                  redis-cli -a $REDISCLI_AUTH --cluster del-node $firstNodeIP:$REDIS_PORT_NUMBER $currentNodeID
+                  echo "delete salve delNode, #?"
                 fi
-                {{- if .Values.tls.enabled }}
-                while ! redis-cli --cluster add-node --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} "${newNodeIP}:${REDIS_TLS_PORT_NUMBER}" "${firstNodeIP}:${REDIS_TLS_PORT_NUMBER}" ${slave[@]}; do
-                {{- else }}
-                while ! redis-cli -a $REDISCLI_AUTH --cluster add-node "${newNodeIP}:${REDIS_PORT_NUMBER}" "${firstNodeIP}:${REDIS_PORT_NUMBER}" ${slave[@]}; do
-                {{- end }}
-                  echo "Add-node ${newNodeIndex} ${newNodeIP} failed, retrying"
+                while ! redis-cli -a $REDISCLI_AUTH --cluster rebalance "${firstNodeIP}:${REDIS_PORT_NUMBER}" --cluster-use-empty-masters; do
+                  echo "Rebalance failed, retrying"
                   sleep 5
                   firstNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-0.{{ template "common.names.fullname" . }}-headless" 120 5)
-                  newNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless" 120 5)
+                  redis-cli -a $REDISCLI_AUTH --cluster fix "${firstNodeIP}:${REDIS_PORT_NUMBER}"
                 done
               done
 
-              {{- if .Values.tls.enabled }}
-              while ! redis-cli --cluster rebalance --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} "${firstNodeIP}:${REDIS_TLS_PORT_NUMBER}" --cluster-use-empty-masters; do
-              {{- else }}
-              while ! redis-cli -a $REDISCLI_AUTH --cluster rebalance "${firstNodeIP}:${REDIS_PORT_NUMBER}" --cluster-use-empty-masters; do
-              {{- end }}
-                echo "Rebalance failed, retrying"
-                sleep 5
-                firstNodeIP=$(wait_for_dns_lookup "{{ template "common.names.fullname" . }}-0.{{ template "common.names.fullname" . }}-headless" 120 5)
-                {{- if .Values.tls.enabled }}
-                redis-cli --cluster fix --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} "${firstNodeIP}:${REDIS_TLS_PORT_NUMBER}"
-                {{- else }}
-                redis-cli -a $REDISCLI_AUTH --cluster fix "${firstNodeIP}:${REDIS_PORT_NUMBER}"
-                {{- end }}
-              done
+              
 
-              {{- end }}
           {{- end }}
           env:
             - name: PACLOUD_DEBUG
